# Ortak Ayarlar
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET} # .env dosyasından Config Server aracılığıyla veya environment variable olarak gelecek

---
# Dev Profili
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/product-service/v3/api-docs/**, /api/v1/products/**
              filters:
                - RewritePath=/product-service/(?<segment>.*), /$\{segment}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway
        url: /v3/api-docs
      - name: Product Service
        url: /product-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# Docker Profili
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/